title:            Site Title
tagline:          A short tagline
description:      Describe your website.
#Comment out url when working locally to resolve base urls correctly
url:              http://localhost:4000
